packages:
  - plugins/*
catalog:
  "@babel/core": ^7.28.4
  "@babel/preset-env": ^7.28.3
  "@rollup/plugin-babel": ^6.0.4
  "@rollup/plugin-commonjs": ^28.0.6
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-strip": ^3.0.4
  "@rollup/plugin-terser": ^0.4.4
  gulp: ^5.0.0
  rimraf: ^6.0.1
  rollup: ^4.50.1
