packages:
  - plugins/*
catalog:
  "@babel/core": ^7.28.6
  "@babel/preset-env": ^7.28.6
  "@rollup/plugin-babel": ^6.1.0
  "@rollup/plugin-commonjs": ^29.0.0
  "@rollup/plugin-node-resolve": ^16.0.3
  "@rollup/plugin-strip": ^3.0.4
  "@rollup/plugin-terser": ^0.4.4
  gulp: ^5.0.0
  rimraf: ^6.1.2
  rollup: ^4.55.1
