packages:
  - plugins/*
catalog:
  "@babel/core": ^7.26.7
  "@babel/preset-env": ^7.26.9
  "@rollup/plugin-babel": ^6.0.4
  "@rollup/plugin-commonjs": ^28.0.2
  "@rollup/plugin-node-resolve": ^16.0.0
  "@rollup/plugin-strip": ^3.0.4
  "@rollup/plugin-terser": ^0.4.4
  gulp: ^5.0.0
  rimraf: ^6.0.1
  rollup: ^4.34.4
