name: Build & Test

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a

      - name: Setup NodeJS
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build packages
        run: pnpm -r build
