name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build & Publish

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build packages
        run: pnpm -r build

      - name: Publish package '@forward-software/reveal.js-caffeine'
        if: contains(github.event.release.name, 'reveal.js-caffeine')
        run: npm publish --provenance --access public
        working-directory: plugins/caffeine
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
